=== laclasse-com/service-cahiertextes/spec/fixtures/ConteneurExportChiffre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by INDEX EDUCATION (INDEX EDUCATION) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.index-education.com/conteneurexportchiffre" targetNamespace="http://www.index-education.com/conteneurexportchiffre" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="EXPORT_INDEX_EDUCATION">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="VERSION" type="xs:string"/>
				<xs:element name="LOGICIEL" type="xs:string"/>
				<xs:element name="CLES">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PARTENAIRE" maxOccurs="2">
								<xs:annotation>
									<xs:documentation>Chiffrement de la clé AES et du vecteur d'initialisation par la clé publique du partenaire</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="NOM" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CONTENU" type="xs:base64Binary">
					<xs:annotation>
						<xs:documentation>Données chiffrées</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="VERIFICATION" type="xs:base64Binary">
					<xs:annotation>
						<xs:documentation>Hash SHA256 du contenu non chiffré</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="DATEHEURE" type="xs:dateTime"/>
				<xs:element name="UAI" type="xs:string">
					<xs:annotation>
						<xs:documentation>UAI de l'établissement</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="NOMETABLISSEMENT"/>
				<xs:element name="CODEPOSTALVILLE"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== laclasse-com/service-cahiertextes/spec/fixtures/Edt_To_LaclasseCom_0134567A.xml
<?xml version="1.0" encoding="UTF-8"?>
<EXPORT_INDEX_EDUCATION xmlns="http://www.index-education.com/conteneurexportchiffre" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.index-education.com/conteneurexportchiffre http://telechargement.index-education.com/export/ConteneurExportChiffre.xsd"><VERSION>1.0</VERSION><LOGICIEL>PRONOTE Monoposte-PRONOTE 2013 - 0.5.14</LOGICIEL><CLES><PARTENAIRE NOM="INDEXEDUCATION">GizCK/X7q5+nQuiyyeCsVs4XWs1WH8TFyJmIU2ckrlYi1FhsU6N+oL/X0WEEaqU1WNpFaiT4biyy
UkwJqh7TXO8XPfRmiRgL4oQS+GuTsqBU9phRTaKKXlwxONh1f5+eTky3glk3KFZ3pDj338nxGHKK
HKuR8yoXHaCYu27TOg60inkhZ7UpBte8eI0SU3adbJFYhU7BQFo/hhCy72NeZMBtbED1V/i/UVt2
7P7TQpWUJLaun5TTkU+D6+28fEd3cuLEEJWIOGbAVjZLYNKVDLqFH7Kq7vCrIISBoUhlpfM8gath
2Z8siug/n4ZqUnVyrl/XvSC/39+xjT0Y7NteNA==</PARTENAIRE><PARTENAIRE NOM="LaclasseCom">CrUtfLGCBO8pikZWv4iEolzKUxyOaUSHMYQhJ3EhLUdVjIwHiRSc1BUZ9jnWvybaLDOJiCKDncbf
+s3xcg6eV03x70EeucF6VxaKI/9d87mLRdCDOTxNxc1EueQiQLcQ01Pg6BPGVksjmiQYWn8vACK+
zjywf0vCpxBqx8vDaQ4t3phcXwjgAiYk5yOWsKSNcpDDdTq/eRLw3JUYizrTlq8VLrC4Vaueix4f
P9RlV59z+GOD2GQeYv7NwCS8gIPlhIwk2Ufiwct5wgv6qv0KrvcwUC07LuxfsKRE1gMVHBEgr7nS
MmLjipjh/9yDoOaQ554F/lgmRyuyaaYvkDTZ+w==</PARTENAIRE></CLES><CONTENU>naU26u/vL75SAOCfVfYdhPCgV5tz9RinmSwpyaIBE0W6NWMCBNkHpyhjOP6DlQU/cG8zo4qP7bhF
JZunhOXqRrQKhSV3MOBoLluR4dRF38zrbcgCKXDeqASskPyjdPWv8V8a7/Mod9a0BgDMsS83Oc7s
oJy4N0D3402zbn5puCszfJUd56+4s25Cj5aOUVIUfx75DBSVVt7Cpme2AcG+LB06uJ6PqhZHRIBK
YtNj5dopy4d/VmzuMD2e3RJiCnPxibLt61g+dIwqvrzH6MSmzRj1yuMDfH4yDBP+F2SXdOQr6ziE
Hjz2Ln/DPzmuS1lxzhqZvOfazgGwR1rLIWF4EXZKIFOAqHeCx+LwLKDgK7M3hTjsxOpgYLmqhRwF
WylANkUJQ1JrUlf95kUSX6/wqs+/9DFHgQuY/3HMeqMq9eVIJX/2GPClZ5cDwJOlc6wVwR7m5uDJ
OVIyGw4Xt3ZTcawXB8wVOZOC95MJFKmH0RwT6oL2bYgrCdDmfGlxid2f40DU+6BETEmavUOiSNR+
hWu1i2EkTLrZ/aa/xX1RIDQ47p93VYsh4b1fHyF/Wz1ojvQ8VY4NdVbzzBGQi3u3Oc+sxERIB4TC
ckiYb2cAMW7+40WUGJXBPlAGYfr4pnpyaWpzOVSSZCgfM/JoBW9++1ox/inZOfYFxEJVcxqQB8eV
pb4wNujR++UXTliaMWmudyP/TuuvRKOeYc1wGxX8Bg1GSU46eFcEO/Guq6tcx3Hwv9HKxu4Wq0h3
RkpjR60ahoM0RdoReJdPofpBiGafLo003dLZrSUccnl5v1Dy3fFWW+15rY7muMCt4QS8fSzLojMY
XKxqRBLhjq9h+C7zNo0Ss3WOHyRZe62G0nDFLKb3+W2yBjsXfb5YQ3OlCGlrcm9Px/tXEdBWSt23
4+RXVy6ZUynwF3FpYDJhtkdoZQbgh8v+mJN1ADRuEZsc2XAAsnbhN5odfuQl9Re3TAXhrY+xQ8Gg
1O9DxbRyKjkDMg2O33OPC6ZVgyvru5le1StSE24iYFtwnNQtAlUhge6q4J7gD3KLwbP/6VjgnUNV
2zwNuV3cR8MbbFi5sodMRoFH0azeecuR1wWdYTCX+ee6njZqQq+fKGMvTmLcy13lDGex4LafrYBQ
iEE6jlR82V7aMIjMQ6sSYpvfk/+tL5Y5dP+eR5tGMlq+8myHf5A/n8uZDAuvV6Z1rCH+nG92EcNa
ET5Sx0b0y3JjjX26r6EWJAIRZwiLbuC7KU4yN5eHW8cvvLq+cElcyb7vpwa25fIM07kA519Y2o3i
f2VbOmrvaav1PQUddY+Py2ZIyJoRP6Faf3nMJNMijiCgjK2FkwF9iZLB7t2q/IyRpTuqHvyfQN22
J43izRQQ5wTHfA7rmgrfnTRiNWnRSgAoqFhMox9v4mFKBi5P2uuAi2cOoArwlkAhxzvx/LXgevYX
UIBzaZWJ4p88axzfa80DB2vMDi+oqcuqioGBr4492Mwf/QPsAYB9MDEz2nUeg0/1seKgPwxkmJM1
OKIYqdhgHTGchXKDYmecMzlYjz8jSrp69xTK2L/A5E+miuvbmi8eeCXq/WDl5eEB8GM4uDb25eIR
5PwH6p993izcoCnDWp6MPqcbb8/MBly4RS218aPuZ233oUi8CbeCB6BjxqwgoayCnb7Cdw2PHXtT
ib5iSk2vLdFV5u+lxIpTXgtb8neFto8k27CzqOukdrC4tGiMRduZSimrdgzWF7G6pHUPhRQUDFSG
UGTBP9a9BVTthJz78j6TIANBbP6DNyKLYTNfK6GVptuXr9DRxHus25/otC/qCWUZnij0MM1dg3vG
GktBfBi9+d5/8K2auo1XedW8t8Ca8jcpDJQx6TmIJx8gVUKL8rny0GKlzKDz5VaU6NtJLCqTNiAx
dh3+2O/mKD/WkwOuLym9MhrkP7LstXusqCEntnoRFUPZu9nU3LzRAqkczhLgXN+LuuanF+Xkvp6l
XoyDixh3wrWPPIdPcV+dZFQcbPYHU0Acm85TUJi91oSwHpwDY68Flj+uAm05Ob54suAIanCNeYtj
fyB8G66JSBgc6S6dk/jGDkBTbg30LsYJ2ZKa1DWDGCF0mSn3gFY942GSF3wqgLeZVd9lGpjQRfyl
xadJhZtO050zNUTJoNwDN0EqpFGqTIkWp6G0DRVVNPQsMTmGFHp+dGRWydpSdgncdSzTqw13VX7g
5lO+DmBkQZ1Nua0avD1JE30bW2OxB4Fb47XMPu/gew0PZ0bGBuiCOWZgwgcgqX3mknL/0EnHZoJS
37rVyb0zYC+EJdqjC+I1oVNR5rhzLhGsMn/DEtCouGCG1Im7GtN85OXYxL7IE2z7mPihbm9+fgL7
qs0XMFlPLsFmvd0GZBf6UDehD7Dsvzwimdhlp0QWLetTOVlGYx/N8/c4+9QpYvKj2o9ddx5kzVyK
j8YegU4ixkVpfTQ1VpJiWoTcbavqHjuDpEn4yCNXYCdGye58NgPiYpV6SnVrBqkRlhwm+m20FYIn
qQnUFAaIpegsdpqvCclRAlRpNteUC98+jscyTM5mibvbivtEJGeM6o8TQ3HXWDJonnIEdVXJkTjr
DO+W2BFLvQocvR44ydqSyWlcEaoWUGY3zblENGxXy45Kyhgm+wtzelR0c9KoLbH2Y9lsFha0aGvY
b9DQEA7QBnx4+/pHHNrpwWBSKgzdoU6muwKA+hjU2cO5f/mUgHQsklr0O5tLOQUOmUdOnTD1mCWh
k4tVM7eVIEFZz1yYRiBdEtTHpRdhhxr42YTi2VYEfQQRKrBSlO5gd0rG/e5Agtx7+FvsNZ78j77S
mXfUagoPv+s66tAmMyOKNnyDsKEsSjXQrEFLJB0zzTvxCMDZDLK8nfMo/sQrTtISdne6jSnpNQwo
vDE/n768RO0B19eQpw9q0uvC5w8YhctC+UdyKqs4BDvB+y9EMdOskm15vel2os8qg812EG5gFWvn
MPB4TFkvjnhyVGGX1HiFvZ8YjF1bCzG1sT+pT2qkHqrZ1ALYn5sUB4+Z+AAY/JXygoH72gd7hBgL
UTphCIGcJs575KHW2bbe+mjcQFu3o2zx1W5i9H6xx6/PKwrf+NKeGK3kxNiRIm9lNd5AdXykOI6h
DWmaY0sZHS/brZ4Ec/PXXZq++uGbArp8HxfQP1/MjR+nwGwkjA0MbODIo4VSowa0f7w/iTVBTbyh
DQECQEzNOAtuEG4WQcf9KU5ppPS+a+zkQt1bpLGGHSkeyFbInFpA78IpAJ5tudhw1zxU0zIRPgCT
gkxI542JadMKQpz2d/dVG/kXC9w3gkA0+Ffusdmy7W9ShEVkWGC1Ts2r/LeZ1vNT1oRv4cs8KvBT
pbKsFvgN9Vhe9cju/RXCuPIdJSXe7ow42prySIlE2taL6ut/j/rEeaPkvGhzBNbiaX+pqk8Vijol
yco8+IPd4BPzp7vsRxNtxN8Kz/cBYNeyjeXKULnymC3DiG3427BCXOrXjx9SDvxRT3pgBlPUBQ2i
o/U/ftfqE9LsDB3oqmtWDo+XW4ONBc4R0fWKHT+1D9kgusNKQtCubLCtfbkGQMaZYZ+gkgCP/mmN
ZtqGpqW1jwnFxnZmdyME+eMEPdufZ1iqKkPbTyQ9sXAZCqOOR5ln4bF15j2iWhj6QbaJTO4flWNS
kkKN1ik6RdHkAvrAXj05PD6vgGKTnmdYJBHloX7ka1AQrduXZNtY0VNy0BkN/O6hVfF3Zv69ycUx
0fqDKYwmDMnjmPPuY3swQK7xkGjxLrXr6v4QPn89rIH6HKxOsbE4fm12+ctw2WuPfxnCl8bfPRqN
y8pVGvxROtCITbv4rQs/s1ag79bzoJdUVU90Cq4KgDC2Pe6MHDHvDrF1dQnmj8MNYmPeKyYwxCvZ
8OnbgtcjjR60/M6VhWqnxLSrYl93KvC7aQJbFSMLCgNswn3s7t8/krV1zi3cfmoLSNjGVxqBO3jD
cNxhRgT5LgiWpZDeVRT637UZsQxJFdwHF057YZQdRe9+8nX6HAPAj3Past4nvvfVV4Agn0BfzmsC
waf1wUfL6g90OGfiuCD4LQqOUlI8QzlZxHpqxMuDY8Yx9MoQQxVujoLrGxpWVzhFzFwcAcyl3JAc
3NLebCvkYwP6LrU46g1m/B6hIx412bAJUF7SQA/tPlRThEpQgi6lt57TlEh0f5otqTBdgtdjec43
Ll+uryGPuRD0i7sDD/65zfsFBkaEcJSnwcj+MWf34tTkwVMftMtDt8Z+VC4dxksUAS8mPyeDFoKJ
yyDNKBNXMYVo6F2UAmJ4ifcv7dZq6p5qc+7B7OKWB1dlHXeBBb1XvzEiUti3RTipjSiuG4hFvfVp
zidp2H/12jw3L+9Rg3jRG/yg+OQEzL3xOhR94wADS7fPaFZHNzB43r9lXfjkdo5ZvuulxkK4CQNv
OEbLrhEQ4dzqrt+UtybqAA53ZyVVkByb+vQ6fREsJFC+iXOXGhE8WRhRGl6T9zH2TYy+6cU380YY
4XRPz22CrV7ypaqi4q2PNpPdkqqClnTD82Cp/3aEc3KgF/isaC1ajaASjn3fIaPQK8AlLTnRJu/g
zn9VViZtGzLaGUHSW3G+K8/QAOpSKGhWjNViB7hKsKRZktqBBgp8qawSxgqA6ZTTM6cdpdpBxQlo
3Gu9YCnKxMy23v772gH13gF8gMyt+PhXMVfIJ7YHNsx7QavuYT7rEdZubxBE4B3Z+RptUNpkgI1c
x0TzIdst3BA2PAtfn98QOYtkVhNGezPRAv/5DwMI2rLUS+cIHzLsJ7we2Zcpq1eYAP22eMa/UjLj
TKzU11BeSqm3XzZgqV51ynGy60UrJVACtsSCqPr24q2HPrQk5EDy2J5XM7k2p5SP525OSMhJzf8D
Jok7N17L+8+bKbVaJmSLAYN4EDdPt8Bwelnb/HRCP94T+Wk5/dZqlmp6ER/QyBO/o5e+0JjT1XmC
DHjAjqnLN8aAfL7kUuNMxOjPUjAC1+nmuRJZL3JKDP/8LqD6M1VTxHhpUuF4KOSoEPsS7jOr1xup
CLIOMmYbmsnfBIbTezxtQ7mT/OUgNxJb+sB+CpLBQROutErQQ0JzL60VuJJh/TOUSP6KA5dwdFgh
c0Wz9ZCvNnS5/ylT7/oaCYQ7hx1Bm0ZemNN9Swn+c57+71F/RRqcT/t1FBDGqFx0PWFGlM2EbAZD
rMmm7KXKGDuBA3Ot7Kzu2KGyYJleF9CmYgQaUKsZbPKoH7vg/TUTRjDM+vxStMStu7rD1iesyO5J
NG/Ce03a1AGv5CSGiSjIIwIN4zC1JrhQn7tvgIfvHgj/Ep5TEA5Sntn6hRKvTZFpT1HiK4nVAnRD
JTMo+onsMyvG9ELEUHZVyi60wpJTwphWuAKhM/k/g14MWmTBd1GEEu/yMV6uUCNPhYQ39MiI1tZp
UrU/TzXn9vbSpW4CgrSXfwJntFCgakuRRWYDAunOzfQB3ClJuvTpb/qK0Z3Wa9o+i5w0ytgt+sgT
g1PuDRyF8adKB2/vT2uraSPoh3BydQEm3IIhsqS8YXRPiUnbc23S6C0z3K9dhThR62GhBOWjRJ8P
bVlcvX2tWQXV50hw+0CiicMDI4hO8xcAWuZ3hSxdFp+lhqgpPQE2uwz0GOEcSXxe4+58CPRbnKjn
7tni8wA1LKedi455Drr5E/mFJB9ecS161ubcIt3Wj1brgV+oxmGUp4IHJX+7mGgp6W6jPxCapFtK
ENIX66AnEz+Gy/jpanw9AdwGKpvkuZ9TwifZ8wzUGCx4rePE2TseNOfwuvCC8x5DHtQj3+BhJSi5
OAJgsOxRkC5GF0GC5OM9h5DbRMXNo1SRIXad9SYC/tbqSb6nnJI9JxkrzX8FjlJPpfxx+/nmoIU6
JlnZGV5My7ib6ngFX2432dENKwGMJSpkIyLTVkeQEVGIy/DQqBetSFNul0ohHZ+qABiLazkSo8FQ
2L5L4GSXX+Tj4wmU2OlCHEGwHazyJfNmKRDkLWqas8SesQdUn7LmVaD0qsmJRpfbVQi/JhrZR+xv
vbTgl9jk9f1xuIVcISDY7NVHMsVkne1zZ2iCK0r1Y8vZRdfMIU6AD3wXP84OPspHU09ozIv98tyx
zLowAJd0WWJThXtfxfEGpqdHgBPEZsttgoXA5OIOc9kZlA7JizSFoFz+57LxQQJIb8xV5S4Mo59C
AqR4R2YU8kYOVSEGftwCvDOBEsJwgr2nW8ADKVYH6O/MuZrIiWxpcx66e4BEc0o5tBCi6kPl/2Rm
JyQfGqD1ZaJrtA/mitNty7A3wkktrLvJpEMLr1Z7lC9BbvxwzMWSC0iEo92BwKtOni+SiMZ+v6xX
mK/znw5zhrfx65k893fwY49XjUr+GJppKZyTLoSRllTU523ACjDxO/JoAShqusuRpoug8HmRVRk0
J1qG00OIwulArdDEo7KZTa9jj2Z9Q+WgAwZvHwjCJJ3LfIqxpcyZnCWskWf0GIr5mao9MjXWp22M
6itHBM4Pic629Lr+/AZ+WaMNa86vuXPoWTwMdpaie6iRGYNpMgbAdn6UHRwfhGLKWtPTNXiQe5mH
IVJMeHNRN/JzZfdpB6SayHbamXHNwBJmhSAoqREX/XRIqRL5OaEDcbxpnMmf2kHz/IHVum36KtD7
KtjwkonYN14Wff9zB/EtGKbAveYTA8WZjpSnPDuU/CLKhbgBvKNxnxLOLegK4eO56o/V0lSHz+7U
4VQND+5TLlU3x6I6S1AVTc5kN6QGVyE1p0o2VV39nnD9cAkLx6pZ4w+hN0TW+ststQe+0P2CAtkS
KVeoyr+GHMQRPEbjmB+2ALO3kGpMUDULe8zM2PnNGO2c0U4H2f9/moueYx5ptd5ApVjqSsPucBbe
ZcthhlAI+MO3M4RyNUZszmKlBWCcVw8OKvYNPBp8wvR13uNSX/YXZesnt3TgDQOURLxtf9vWGImj
Af0g5NqBwtwC581RoiRM2nPfz6wNWHg1yH9dtgYXLqOLRo1Mz3amFcVoV9tYnCH+RK9VILdQ/BET
8iFbIweapsWawk7au3bvxusu509gf7nqDJN3MVP9LcNWOcVFzJlTXRNRNOqHsF3RTSgD70nVsKAR
r6iAo/WbETjyTbwZNNJIqQhFFwVqthyaC1CASSzGUmDSTVZvElVqyr9tUdyz+LJIKAkCJ7bGhuA4
rtV4v4HHqqpYFk6KFYAxcNqSE/GNPwbRsn4SHoZ925E9M653kCglrrAkGwvvdmLjMmocSzYlKivU
S0gmramjkNQpDz0mT2fVlCM4hpU7MsdG1xVHU0b4wPF/kgZsImk7CMvtssGaLP6xIJCnCfaFul0t
GvTT8U40uu4Fz/U4fS82s8f1yy0FRqsuaAFwKMG551I9OEIFbc/V2GwujOvzjkW7+Mp8rQNEvgZW
YvCzT7RdIQL/UPS6A/Gjtl+mrVNRg2LZGiy0umfGBs53innGn2h84I3cRxaXFlmqsgTM5/ekigJ3
f3r0ipgNyJw0XIxQ513ymZnfSUn4Xilwcf9Z87ZulnLumPdPWdgb1CU9wu+xYK/3MmDo1yB8WKu9
sAbjnub+Mw48Z6LO+wW99CqjLD40dLnLlPZ/7VzhE86VVz0PDIPhAPTl1C8oDT1l2yo10V/uxtvA
X7nc3tZC7IvbAW7tAW3a1DAmUvXiias1KmZzjbx/1qJAAepQmIYCnGzFqqXLnIXfJNFSR+4P24Dt
6X5aIljBFBNuPZC2zI9TsS7gHWthgTT0SgmYuxscu+JM1+hmcmZ9rcGIeO+UVVAJCg3eaiaTLG5S
8CJwJL68P0JPJgf0t2r9wDvNTobbAh2OMUXrpX6vV1/DLxQ6DpBwA0+fhRxF6rVbZOorwo0QfGZ1
giIw5rjiCGm9OwUVmwZCf+aPQ/OhOlASWjhaezV9AG9MrthQenkvoMgenHrTtcVi9IHlQtwyXORE
U0ngoO56HnT4KArjEPN7RcNMo7O19A8GbCPop/SeT/EboPN32PFl4NSp4QFPkvpgN5m0HM104Nrp
ew5pOSMZmRGGoXPC75xpRogisFz/4sqohT12ovWBI1Ll/66oiMSjw/eHlXDZRBceeQP1+oZ4Tv65
srk0aJNmSd/gp8GFZAI4BxBeD7pfOm7aSx86Y4uGUElJxNLeiKAJ9d2S9IavaPI9uCvaPORYo/lu
y5+tcXFpX0Raw5mSa7XNEvJFfxuQBNjiN66W7Arz8f5+GFagQd1ITDuEkDlljiSrjjxoyPp2Gs54
G4ZWLpZEWZ/54SMCNq6oYrGSTjIO0HQzWRV+fMW12Wy0KTwuNNL6z1meYdTDwYREJb9g3X9ZVWJq
Spjif1MUW/XumL5TuKzGxlkIAfaZs0DfOhJTsiznpeEa5Ea+zGOjDnhyKJCjABjYk8OzC3a+3TNQ
PsCE13Os+qpIfOj7pAcxjf4nJb7bwZa0C9xrMdAdK90m3xNCYRQC4SlaDh1Vl/u5fQRNiYj94N+d
tcZiy3R6LP5rJ+1V+L5yimvrSJsyPqEKeeAVcXvkXDDU1vytjC4PSfdtrKB+/dVZk5uj7jKtm33m
